language: go

go:
  - 1.13

services:
  - docker

before_install:
  - mkdir bin
  - env GOOS=linux GOARC=amd64 go build -o bin/static-server
  - docker build -t zacsketches/static-server .
  - docker image ls
