language: go

go:
  - 1.13

services:
  - docker

script: 
  - mkdir bin
  - env GOOS=linux GOARC=amd64 go build -o bin/static-server

after_script:
  - docker build -t zacsketches/static-server .
  - docker image ls
