language: 
  - go
  - node_js

go:
  - 1.13

node_js:
  - 13.1.x

services:
  - docker

install:
  - go get -t
  - cd frontend
  - npm install -g create-react-app
  - npm install
  - create-react-app --version
  - npm run build
  - cd ..
  - echo $PWD
  - cp -r frontend/build/ www/
 

# before_script:
#   - travis_install_go_dependencies $TRAVIS_GO_VERSION

# The golang container that will be built is a linux OS for an amd64 architecture
script: 
  - mkdir bin
  - pwd
  - ls -alF
  - env GOOS=linux GOARCH=amd64 go build -o bin/static-server

after_script:
  - docker build -t zacsketches/static-server .
  - docker image ls
