language: 
  - go
  - node_js

go:
  - 1.13

node_js:
  - 13.1.x

services:
  - docker

after_install:
  - npm install -g create-react-app

before_script:
  - cd frontend
  - npm run build
  - cd ..
  - echo $PWD
  - cp -r frontend/build/ www/

# The golang container that will be built is a linux OS for an amd64 architecture
script: 
  - mkdir bin
  - env GOOS=linux GOARC=amd64 go build -o bin/static-server

after_script:
  - docker build -t zacsketches/static-server .
  - docker image ls
